### ISSUE TITLE
Beautify the "incorrect" grey box

### ISSUE THREAD

**Issue by FourierTransformer** [FourierTransformer/DailyMath#6]
Too many buttons? There's something off with it

**Comment by hissingpanda** [comment]
Better?? (Show description/hint maybe on other page before submission?)

![selection_003](https://cloud.githubusercontent.com/assets/7660115/11362462/4acce44a-9259-11e5-9bbb-15f393901aee.png)

**Comment by FourierTransformer** [comment]
That's nice - looks super clean! I think I'll try to get that working. After you click on "Show Answer", I think I'll have the button become "Show Description".

**Comment by FourierTransformer** [comment]
Complete as of 5f85b946bce0e9079ae35312229b983a245b5003
